remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [OBSRAI: Open Benchmark for Spatial Representations for Artificial Intelligence]
description: [Welcome to the OBSRAI repository, a comprehensive resource designed to advance the research and development of spatial representation models in artificial intelligence.]