remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [OBSRAI: Open Benchmark for Spatial Representations for AI]
description: [OBSRAI is a benchmark for spatial representations for AI.]